### ISSUE TITLE
Using this from an addon project

### ISSUE THREAD

**Issue by jackmatt2** [plusacht/ember-bootstrap-datetimepicker#10]
I am pulling this into an addon project which I share among a number of sub projects.  I have found that I need to run `ember g ember-bootstrap-datetimepicker` to pull down all the bower dependencies or I get errors about missing bower dependencies.  So If I had 10 subprojects plus the single addon project, I would need to do this 11 times.

It is possible to automatically serve these bower dependencies to consuming applications of an addon project?

**Comment by claudiocro** [comment]
I close this issue because it's old and I can not help.
