### ISSUE TITLE
Upgrade broke custom icons

### ISSUE THREAD

**Issue by shinzui** [plusacht/ember-bootstrap-datetimepicker#14]
My project does not include bootstrap's glyphicons and the code to customize the icons no longer works. 

```javascript
BsDateTimePicker.reopen({
  icons: {
    time: "fa fa-clock-o",
    date: "fa fa-calendar",
    up: "fa fa-arrow-up",
    down: "fa fa-arrow-down"
  }
});
```

**Comment by kmmathis** [comment]
Having the same issue. What file / where in your code do you call BsDateTimePicker.reopen() ?

**Comment by shinzui** [comment]
In a custom domain-specific component which wraps ember-bootstrap-datetimepicker.

**Comment by claudiocro** [comment]
This should work with the latest version. Can you confirm that?

**Comment by shinzui** [comment]
It's working now.
