### ISSUE TITLE
Impossible to clear value?

### ISSUE THREAD

**Issue by timolehto** [plusacht/ember-bootstrap-datetimepicker#16]
It seem that it is not possible to reset the value of this picker to null/undefined/etc. If you click on the icon it automatically selects a date for you. Which is a little bit odd, but ok... But then the impossible to live with problem is that then there is no undoing "your" selection. If you want another date, that's ok. Just type or choose one from the calendar, but if you decided you didn't want to specify data at all your out of luck. You can clear the input field and it looks like the date is gone, but that has no effect on the internal state of the component nor the fields bound to the components date. Am I missing something obvious or how can this be?

**Comment by claudiocro** [comment]
If you want to prevent the picker from automatically setting the current date you can set the "useCurrent" option to false. 

ember-bootstrap-datetimepicker supports all options from "eonasdan-boostrap-datetimepicker":
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#usecurrent

Clearing the value is working with the latest version 0.3.0 @timolehto can you config this?
