### ISSUE TITLE
A fragment cannot be pushed into a buffer that contains content

### ISSUE THREAD

**Issue by givanse** [plusacht/ember-bootstrap-datetimepicker#20]
I followed the installation instructions and added the component like this:

    {{bs-datetimepicker date=model.createdBefore format='MM-DD-YYYY'}}

The app now throws:

    Assertion Failed: A fragment cannot be pushed into a buffer that contains content

Any ideas?

**Comment by claudiocro** [comment]
Can you make a small reproduction with JSBin or repo? So we can try to help track this?

What ember.js version are you using?

**Comment by givanse** [comment]
The environment where I first saw the error is:

    "ember": "1.10.0"
    "ember-cli": "0.2.0-beta.1"

So, I thought that the big difference between versions could be causing the problem. I went ahead and upgraded the addon to the latest stable releases (I can submit the PR once we figure this out).

This is the branch with the changes: https://github.com/givanse/ember-bootstrap-datetimepicker/tree/bump-libs

    "ember": "1.10.0"
    "ember-cli": "0.2.0"

Still saw the same error by running the dummy app.

**Comment by givanse** [comment]
The only info I've found about this: https://github.com/emberjs/ember.js/issues/10400

**Comment by claudiocro** [comment]
The latest commit seems to take care of the issue, can you confirm it?

https://github.com/plusacht/ember-bootstrap-datetimepicker/commit/0ce680638607e726cbac9273ea8c67f8262ec1be

**Comment by givanse** [comment]
I rebased the branch, served the dummy app and the issue is not resolved yet.

**Comment by givanse** [comment]
The error disappears if we comment out `setUnknownProperty()`

https://github.com/givanse/ember-bootstrap-datetimepicker/blob/bump-libs/addon/components/bs-datetimepicker.js#L139

**Comment by claudiocro** [comment]
Should be gone now, I has committed the wrong source.

**Comment by givanse** [comment]
Fixed with 4d25907822b75094599190429d9b43fa68802c71
