### ISSUE TITLE
tabs everywhere

### ISSUE THREAD

**Issue by givanse** [plusacht/ember-bootstrap-datetimepicker#21]
![](http://s2.quickmeme.com/img/68/687f6a0e3eac26b3036c84403cf5c2000f37804ef77fe2b2cdba9e2e9178e39c.jpg)

:yum:

**Comment by claudiocro** [comment]
https://github.com/plusacht/ember-bootstrap-datetimepicker/commit/e71941523dc9ec3413e132c18b682b2df746d800

:blush:
