### ISSUE TITLE
No icon button

### ISSUE THREAD

**Issue by btecu** [plusacht/ember-bootstrap-datetimepicker#23]
It would be useful to have the option to opt out of the icon button.
http://eonasdan.github.io/bootstrap-datetimepicker/#no-icon-input-field-only

**Comment by jkatsnelson** [comment]
I made a PR for this

**Comment by claudiocro** [comment]
The option has been added with this commit https://github.com/plusacht/ember-bootstrap-datetimepicker/commit/806c8eab67c82826a2c4c59870e571bff9e275ec
Thanks to @jkatsnelson
