### ISSUE TITLE
Using locales

### ISSUE THREAD

**Issue by haggins** [plusacht/ember-bootstrap-datetimepicker#28]
Hello,

I try to use another language without success in ember-cli:

In .hbs file:

    {{bs-datetimepicker date=reportDate format='DD.MM.YYYY' maxDate=maxDate locale="de"}}

In Brockfile.js:

    app.import("bower_components/moment/min/moment.min.js");
    app.import("bower_components/moment/locale/de.js");

Javascript console now outputs:

    Uncaught TypeError: locale() locale de is not loaded from moment locales! bootstrap-datetimepicker.js:1504

However, it's possible to access *moment.localeData('de')* directly via Javascript console.

Any idea what I missed?

Kind regards
haggins

**Comment by miguelcobain** [comment]
This addon could have an option to choose which locales to load. Meanwhile, in your brocfile, just include:

```js
app.import(app.bowerDirectory + '/moment/moment.js');
app.import(app.bowerDirectory + '/moment/locale/de.js');
```

This way you're manually including moment locale file.

**Comment by claudiocro** [comment]
Locals and other dependencies should be included by the application itself.

Also the current option to include booststrap for the addon will be removed.
