### ISSUE TITLE
Uncaught Error: Could not initialize DateTimePicker without an input element

### ISSUE THREAD

**Issue by rafaltrojanowski** [plusacht/ember-bootstrap-datetimepicker#32]
I updated ember cli to 0.2.7 and I now I'm getting error when render template with this line:

bs-datetimepicker date=startedAtDate format='YYYY-MM-DD' disabled=disableStartedAtInput

I have ember-bootstrap-datetimepicker 0.4.1 and:
DEBUG: -------------------------------
ember.js:15358 DEBUG: Ember                       : 1.8.0
ember.js:15358 DEBUG: Ember Data                  : 1.0.0-beta.19
ember.js:15358 DEBUG: Handlebars                  : 1.3.0
ember.js:15358 DEBUG: jQuery                      : 1.11.3
ember.js:15358 DEBUG: Ember Simple Auth           : 0.8.0-beta.2
ember.js:15358 DEBUG: Ember Simple Auth OAuth 2.0 : 0.8.0-beta.2
ember.js:15358 DEBUG: -------------------------------

With inline option template is rendered with input without possibility to select date.
I don't have idea how fix this, could you help me?

**Comment by claudiocro** [comment]
It look like someting is wrong the the generated HTML.
The generated HTML should look something like this:
```html
<input id="ember409" class="form-control" name="ember389" type="text">

**Comment by rafaltrojanowski** [comment]
Thanks! I will check it. I successfully render template via block:

{{#bs-datetimepicker date=date2}}
      {{view Ember.TextField disabled=disabled class="form-control" name="Date" placeholder="Date"}}
{{/bs-datetimepicker}}

but it is clean input without picker. Maybe it's something with handlebars version compatibility.

**Comment by rafaltrojanowski** [comment]
I downgraded to 0.4.0 and now error is different:
Uncaught TypeError: Cannot read property 'date' of undefined

**Comment by rafaltrojanowski** [comment]
Thanks! Installing broccoli-ember-hbs-template-compiler and downgrade to 0.4.0 resolved problem

**Comment by jackmatt2** [comment]
Also getting this error on `ember@2.4.4`.  I don't think having to install third party dependencies and downgrade dependencies is a viable solution.
