### ISSUE TITLE
JS error when trying to clear DateTimePicker

### ISSUE THREAD

**Issue by satpai1215** [plusacht/ember-bootstrap-datetimepicker#33]
I have the 'showClear' option set to true on my template.  But when I try to click the clear button I am getting ```ev.date.isSame is not a function```.  In addition, the value of the datetimepicker is getting reverted when trying to clear.  I have ```keepInvalid=true``` but the datetimepicker is not allowing for blank or null values still.  Does ```keepInvalid=true``` work with the Ember addon?  Thanks in advance

**Comment by satpai1215** [comment]
Related to this issue I found that ```ev.date``` is returning false when the datetimepicker value is null or undefined.  This means that ```Ember.isNone(ev.date)``` returns false in the code below and the else if conditional is being run, which throws the error above.  Changing the first conditional from ```Ember.isNone(ev.date)``` to ```!ev.date``` fixes the issue.

```
bsDateTimePicker.on("dp.change", function(ev) {
      if(Ember.isNone(ev.date)) {      //This returns false because ev.date returns false when undefined
        self.set("date", undefined);
      } else if (!ev.date.isSame(self.get('date'))) {
        if(self.forceDateOutput) {
          self.set("date", ev.date.toDate());
        } else {
          self.set("date", ev.date);
        }
      }
    });
'''

**Comment by sharavsambuu** [comment]
hey satpai1215 thank you, I was having similar issue.

**Comment by claudiocro** [comment]
I added a test case for this issue, but the test does not fail. Can you have a look if the test represents your case? 

#35

**Comment by satpai1215** [comment]
thanks for getting back to me.  The test seems to represent my case properly because it's failing locallly for me.  I'm not sure how best to approach figuring out what's wrong but here's a screenshot of the failing test and the error log.  It's throwing the same ```ev.date.isSame is not a function``` error

<img width="1259" alt="screen shot 2015-07-03 at 2 30 00 pm" src="https://cloud.githubusercontent.com/assets/2665473/8505008/a08a4b8c-2190-11e5-9b4d-91f201358f22.png">

Error Trace:
```
TypeError: ev.date.isSame is not a function
    at HTMLDivElement.<anonymous> (bs-datetimepicker.js:54)
    at HTMLDivElement.jQuery.event.dispatch (jquery.js:4435)
    at HTMLDivElement.jQuery.event.add.elemData.handle (jquery.js:4121)
    at Object.jQuery.event.trigger (jquery.js:4350)
    at HTMLDivElement.<anonymous> (jquery.js:4901)
    at Function.jQuery.extend.each (jquery.js:374)
    at jQuery.fn.jQuery.each (jquery.js:139)
    at jQuery.fn.extend.trigger (jquery.js:4900)
    at notifyEvent (bootstrap-datetimepicker.js:445)
    at setValue (bootstrap-datetimepicker.js:811)
onerrorDefault @ ember.debug.js:27271
__exports__.default.trigger @ ember.debug.js:47616
Promise._onerror @ ember.debug.js:48628
publishRejection @ ember.debug.js:46859
(anonymous function) @ ember.debug.js:27239
Queue.invoke @ ember.debug.js:871
Queue.flush @ ember.debug.js:936
DeferredActionQueues.flush @ ember.debug.js:741
Backburner.end @ ember.debug.js:166
Backburner.run @ ember.debug.js:221
run @ ember.debug.js:15925
(anonymous function) @ ember.debug.js:35126
```

**Comment by miguelcobain** [comment]
I'm having the same issue as described.
