### ISSUE TITLE
Ember 1.13

### ISSUE THREAD

**Issue by btecu** [plusacht/ember-bootstrap-datetimepicker#36]
In 1.13 `template` triggers a deprecation warning. For checking if it's a block, `hasBlock` can be used.
~~However, it looks like the check is not necessary anyway, since `bs-datetimepicker` component doesn't support blocks anyway, so this should be removed:~~
```
{{#if template}}
  {{yield}}
{{else}}
```

**Comment by claudiocro** [comment]
Fixed by #39

**Comment by miguelcobain** [comment]
I believe that the deprecations aren't gone yet:

```
DEPRECATION: Using `{{view}}` or any path based on it ('workwise-client/templates/components/bs-datetimepicker.hbs' @ L4:C2) has been deprecated. [deprecation id: view.keyword.view]
See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
```

It comes from the `{{view` in the component's tempate.

**Comment by btecu** [comment]
That requires a bigger refactor from `view` to use a `component`.
It would be nice if we could get that in `0.5.0`.

**Comment by claudiocro** [comment]
I would like this addon to be free of deprecation warnings. I will start working on this on a separate branch.

**Comment by miguelcobain** [comment]
Can we reopen this?
