### ISSUE TITLE
Setting maxDate/minDate to null raises an error.

### ISSUE THREAD

**Issue by rmariuzzo** [plusacht/ember-bootstrap-datetimepicker#37]
For the following code:

```html
{{bs-datetimepicker date=from maxDate=date format="MM/DD/YYYY HH:mm" sideBySide=true}}
```

If `date` equals to `null` an error will be raised. However, if `date` equals to `undefined` everything will be fine. I consider setting a `null` value should work as it would work if set to `undefined`.

Stack trace: 

```
Uncaught TypeError: maxDate() Could not parse date parameter: null
  picker.maxDate @ bootstrap-datetimepicker.js:1415
  (anonymous function) @ bootstrap-datetimepicker.js:1266
```

Do you want a PR for this?

**Comment by claudiocro** [comment]
The `eonasdan-datetimepicker` does not allow `null` for minDate/maxDate. I think it's wrong to do validations / transformation for `eonasdan-datetimepicker` options in this addon.

This belongs to http://eonasdan.github.io/bootstrap-datetimepicker in my opinion.

**Comment by rmariuzzo** [comment]
Ok, it makes sense.
