### ISSUE TITLE
Path or pattern "bower_components/ember-cli-moment-shim/moment-shim.js" did not match any files

### ISSUE THREAD

**Issue by oswaldoacauan** [plusacht/ember-bootstrap-datetimepicker#43]
Ember-cli version 0.2.7

**Comment by btecu** [comment]
The issue is that `ember-cli-moment-shim` has been migrated from `bower` to `npm` in the last version.

**Comment by jeancdc** [comment]
+1

**Comment by oswaldoacauan** [comment]
A quick fix is to force on your `bower.json` the version `0.2.0` of `ember-cli-moment-shim`.

```
"ember-cli-moment-shim": "0.2.0",

**Comment by jeancdc** [comment]
So, we must to wait a newer version of ember-bootstrap-datetimepicker in order to use the new version of ember-cli-moment-shim?

**Comment by jasonmit** [comment]
https://github.com/plusacht/ember-bootstrap-datetimepicker/pull/44

**Comment by jcope2013** [comment]
status of using this alongside 0.6.0 of ember-cli-moment-shim? https://github.com/jasonmit/ember-cli-moment-shim, do we still need the bower listing and import?

**Comment by jasonmit** [comment]
It's an addon now, so npm dep only and yes to import.  Import as 'moment'

**Comment by jcope2013** [comment]
@jasonmit do you know where to import moment? i am getting Uncaught bootstrap-datetimepicker requires Moment.js to be loaded first, prolly get rid of this in the index.js but not sure where to put import now

```
included: function(app) {
    this._super.included(app);

    app.import(app.bowerDirectory + '/ember-cli-moment-shim/moment-shim.js', {
      exports: {
        moment: ['default']
      }
    });
  }
```

**Comment by btecu** [comment]
I've ended up writing a new addon that uses the latest versions of the dependencies (`bootstrap-datetimepicker` and `ember-cli-moment-shim`).
Also, it doesn't have any `view` so you don't get any deprecation warnings with `ember 1.13+`.

Feel free to give it a try - https://github.com/btecu/ember-cli-bootstrap-datetimepicker

**Comment by claudiocro** [comment]
@btecu Thank your for answering and helping in this. Do you want collaboration rights for this project? So you could help out?

**Comment by jasonmit** [comment]
@jcope2013 'ember install ember-cli-moment-shim'

**Comment by jasonmit** [comment]
And remove the app.import, you will not be needing that anymore.

**Comment by jcope2013** [comment]
@jasonmit hmm i give it another shot later but that sounds similar to what i tried, do you have it working alongside the npm package? I was getting this error inside the bootstrap-datetimepicker ``` Uncaught bootstrap-datetimepicker requires Moment.js to be loaded first ```

**Comment by jasonmit** [comment]
Push what you have to a branch.  I don't know anything about bootstrap date picker to help until I see what you have.

**Comment by jcope2013** [comment]
this is what I npm linked into my app https://github.com/jcope2013/ember-bootstrap-datetimepicker

I manually do the imports in my own app so i removed them from the index.js, maybe that is the culprit

**Comment by btecu** [comment]
@claudiocro I thought about trying to solve this issue, but then I saw that there was a pull request (#44) that stayed open for over two weeks and I wasn't sure if you were still interested in this project or maybe if you have the time for it. Additionally, this addon relies heavily on the old ember view and causes deprecation warnings in 1.13. In 2.0 is not going to work unless you specifically pull the legacy-view. So it seemed that it would be better to start from zero. It's not that much code any way...

**Comment by jasonmit** [comment]
@jcope2013 https://github.com/plusacht/ember-bootstrap-datetimepicker/pull/45/commits should fix the issue

**Comment by claudiocro** [comment]
#45 has been comited and should fix this
