### ISSUE TITLE
Can't force the picker to show/use UTC date?

### ISSUE THREAD

**Issue by sacarino** [plusacht/ember-bootstrap-datetimepicker#49]
Hi there.

This is an excellent addon for ember-cli, but I seem to be hitting a wall with the TZ used by the picker itself.

I have a ISO8601 activityDate `2015-08-27T21:27:00Z` (example) being returned by my backend, and successfully loaded as `moment.utc(value)`. However, as soon as the picker's value changes activityDate, it's now in my local tz and NOT still in UTC. I think what's happening here is that the picker's date value is instantiated as a new moment, which is where the local TZ is coming from. 

I need this to display in UTC, regardless of the browser's current TZ. Is there an option that I'm missing here? Or am I borking up moment?

**Comment by jasonmit** [comment]
https://github.com/plusacht/ember-bootstrap-datetimepicker/pull/50/files will fix this since it implements an action versus setting the value for you.

**Comment by Kilowhisky** [comment]
Not quite..

The datepicker appears to create a new date based off the local time when the action is triggered. It disregards the timezone in the incoming date too and assumes its local.

So for example if i send in this to the date picker.
`moment.utc('2017-01-01 7:00:00Z')`

If i do nothing to the date but get it to trigger the action It will output this (assuming i'm -7 time zone)
`moment.format() == '2017-01-01T07:00:00-07:00'`
``moment.utc().format() == "2017-01-01T14:00:00Z"`

That doesn't match what i sent in..
