### ISSUE TITLE
Resetting a bound date does not work

### ISSUE THREAD

**Issue by jackmatt2** [plusacht/ember-bootstrap-datetimepicker#5]
I am using this component on a search screen where the user can select a `from` and `to` date among a number of other options.  I have a `reset` button which resets the model.  What I have found is that the date binding does not reset to blank and retains the original value, everything else is reset as expected.

````javascript
actions : {
    reset : function() {
       this.set('model', Ember.Object.create({}));
   }
}
````

**Comment by claudiocro** [comment]
The latest version v0.2.8 should fix it.
