### ISSUE TITLE
Do not package travis-phantomjs (reduce installed size more than 1000 times)

### ISSUE THREAD

**Issue by ChALkeR** [plusacht/ember-bootstrap-datetimepicker#52]
_Disclaimer: I am not a user of this package, this was found during mass npm package downloading._

Atm, your npm package `ember-bootstrap-datetimepicker` `0.6.0` has packaged size **37 MiB**, and installed size **70.55 MiB**.

**70.50 MiB** of that is inside the `./travis-phantomjs` dir. 17 MiB of that is the file `./travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2`.

I suspect that those files were accidently packaged.

**Comment by jasonmit** [comment]
There is one dep and it's needed (babel).  Also not sure why your bot is flagging phantomjs in travis ci builds.

**Comment by ChALkeR** [comment]
`phantomjs-2.0.0-ubuntu-12.04.tar.bz2` is needed?

**Comment by ChALkeR** [comment]
```bash
mkdir test
cd test
wget https://registry.npmjs.org/ember-bootstrap-datetimepicker/-/ember-bootstrap-datetimepicker-0.6.0.tgz 
tar -xf ember-bootstrap-datetimepicker-0.6.0.tgz 
du -hs package/*
```
> 12K     package/addon
24K     package/app
12K     package/blueprints
4,0K    package/CHANGELOG.md
12K     package/config
4,0K    package/index.js
4,0K    package/LICENSE.md
4,0K    package/package.json
4,0K    package/publishToGHPages.sh
4,0K    package/README.md
**71M     package/travis-phantomjs**

**Comment by ChALkeR** [comment]
@claudiocro

**Comment by jasonmit** [comment]
Oh, looks like @claudiocro does deployments directly from the CI box.  He'll need to modify the the travis.yml to remove travis-phantom before deployment.

Reopening.
