### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by celicoo** [plusacht/ember-bootstrap-datetimepicker#59]
I would like to propose language support. The add-on is great , but unfortunately I can not use because the users are brazilian.

**Comment by jasonmit** [comment]
I'm not following, ember-bootstrap-datetimepicker does not contain anything language specific.  The actual bootstrap component, bootstrap-datetimepicker, supports a locale option.  Unusure if this satisfies your requirements.  If you need further customization around language, you should request it https://github.com/Eonasdan/bootstrap-datetimepicker

**Comment by jasonmit** [comment]
Also, all the text does seem to be customizable downstream in bootstrap-datepicker.
