### ISSUE TITLE
Datepicker hidden?

### ISSUE THREAD

**Issue by samsebastian** [plusacht/ember-bootstrap-datetimepicker#65]
I've noticed that is some circumstances the datepicker is hidden by it's container.

Example below, is there a way to make the datepicker show above the container?

![image](https://cloud.githubusercontent.com/assets/9647970/12706429/b84cd900-c8d0-11e5-994d-5d65906d444b.png)

**Comment by jasonmit** [comment]
This addon does not ship with CSS, so it's either your project or stylesheets within https://github.com/Eonasdan/bootstrap-datetimepicker

Please make that determination and report to bootstrap-datetimepicker if it applies.
