### ISSUE TITLE
How do I initialize the datepicker on route navigation?

### ISSUE THREAD

**Issue by NullVoxPopuli** [plusacht/ember-bootstrap-datetimepicker#66]
the date picker works if I refresh the page (or just manually type in the URL that has the datepicker)

but if I navigate to it, the datepicker isn't initialized, and the text field is just a text field.

Here are the two templates that I navigate between:

this one is at /events/:id//edit/
https://github.com/NullVoxPopuli/aeonvera-ui/blob/upgrade-to-ember-2/app/templates/events/show/edit/index.emblem

and

this one is at /events/:id/edit/options
https://github.com/NullVoxPopuli/aeonvera-ui/blob/upgrade-to-ember-2/app/templates/events/show/edit/options.emblem

If I type one of those paths in to the address bar, and then click a link-to that takes me to the other route, the second route's date-time-pickers don't work.

**Comment by jasonmit** [comment]
Links are dead, closing
