### ISSUE TITLE
NPM publish

### ISSUE THREAD

**Issue by jasonmit** [plusacht/ember-bootstrap-datetimepicker#72]
@plusacht/owners please npm publish 1.0.3 and 1.0.4 (master) or feel free to add me jason.mitchell.w (at) gmail.com

**Comment by claudiocro** [comment]
I will do it in the next 48 hours.

I use the npm `semantic-release` library to publish this addon, that has shown to be troublesome. I will change that and give you also publish right's if you want @jasonmit .

**Comment by claudiocro** [comment]
Ahh, you already answered my question :smile:

**Comment by claudiocro** [comment]
@jasonmit you have `npm publish` rights. Ff you can wait until i remove the `semantic-release` stuff, and if not just release it. Else I will do it in the next 48 hours.

**Comment by offirgolan** [comment]
friendly bump :smiley_cat:

**Comment by jasonmit** [comment]
I didn't have rights when I opened the issue, if that changed since then I'll version tonight

**Comment by claudiocro** [comment]
done!

**Comment by offirgolan** [comment]
Fantastic! Thank you 😬

On Thursday, April 7, 2016, Claudio Romano <notifications@github.com> wrote:

> done!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/plusacht/ember-bootstrap-datetimepicker/issues/72#issuecomment-206786462>
>


-- 
Thanks,
Offir Golan
