### ISSUE TITLE
how to show the icon in the input field?

### ISSUE THREAD

**Issue by tommyblue** [plusacht/ember-bootstrap-datetimepicker#8]
I followed the instructions but the `input-group-addon` span remained empty (no icon). I had to create the `app/templates/components/bs-datetimepicker.hbs` file in my ember-cli app to show it:

```
<div class="datetimepicker input-group date">
  {{view textFieldClass classNames="form-control" disabled=disabled name=textFieldName}}
  <span class="input-group-addon">
    <span class="glyphicon glyphicon-calendar"></span>
  </span>
</div>
```

Other icons are ok, just this was empty. Browsing the code I didn't find anything about setting the icon. What I'm missing?

**Comment by claudiocro** [comment]
This was an issue, that 0.2.8 has resolved.
