### ISSUE TITLE
I18n usage

### ISSUE THREAD

**Issue by erwin16** [plusacht/ember-bootstrap-datetimepicker#80]
Coming from Rails, I have some issue in localizing my project ...  hw can I use 18n, with the bootstrap-datetimepicker ? thanks for adding a paragraph on it in the README ...

**Comment by jasonmit** [comment]
You want to localizes the labels?

**Comment by jasonmit** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#locale and feel free to bring in moment w/ locales through ember-cli-moment-shim
