### ISSUE TITLE
After i installed ember-bootstrap-datetimepicker, i get this error message. Please help me.

### ISSUE THREAD

**Issue by umeshblader3** [plusacht/ember-bootstrap-datetimepicker#88]
DEPRECATION: `Enumerable#contains` is deprecated, use `Enumerable#includes` instead. [deprecation id: ember-runtime.enumerable-contains] See http://emberjs.com/deprecations/v2.x#toc_enumerable-contains for more details.
    registerHandler/HANDLERS[type]@http://0.0.0.0:3001/assets/vendor.js:21555:7
    raiseOnDeprecation@http://0.0.0.0:3001/assets/vendor.js:21475:7
    registerHandler/HANDLERS[type]@http://0.0.0.0:3001/assets/vendor.js:21555:7
    invoke@http://0.0.0.0:3001/assets/vendor.js:21571:7
    deprecate@http://0.0.0.0:3001/assets/vendor.js:21539:5
    deprecate@http://0.0.0.0:3001/assets/vendor.js:33746:12
    _Mixin$create.contains@http://0.0.0.0:3001/assets/vendor.js:48696:7
    _buildConfig@http://0.0.0.0:3001/assets/vendor.js:72685:14
    didInsertElement@http://0.0.0.0:3001/assets/vendor.js:72594:52
    superWrapper@http://0.0.0.0:3001/assets/vendor.js:39640:17
    CoreView<.trigger@http://0.0.0.0:3001/assets/vendor.js:58566:16
    superWrapper@http://0.0.0.0:3001/assets/vendor.js:39640:17
    Renderer.prototype.didInsertElement@http://0.0.0.0:3001/assets/vendor.js:29409:7
    Renderer_dispatchLifecycleHooks@http://0.0.0.0:3001/assets/vendor.js:29321:11
    Renderer_renderTopLevelView@http://0.0.0.0:3001/assets/vendor.js:29295:7
    Queue.prototype.invoke@http://0.0.0.0:3001/assets/vendor.js:15823:9
    Queue.prototype.flush@http://0.0.0.0:3001/assets/vendor.js:15889:11
    DeferredActionQueues.prototype.flush@http://0.0.0.0:3001/assets/vendor.js:15697:11
    Backburner.prototype.end@http://0.0.0.0:3001/assets/vendor.js:15011:9
    Backburner.prototype.run@http://0.0.0.0:3001/assets/vendor.js:15133:13
    Backburner.prototype.join@http://0.0.0.0:3001/assets/vendor.js:15153:16
    run.join@http://0.0.0.0:3001/assets/vendor.js:38605:12
    run.bind/<@http://0.0.0.0:3001/assets/vendor.js:38668:14
    resolve/</mightThrow@http://0.0.0.0:3001/assets/vendor.js:8184:21
    resolve/</process<@http://0.0.0.0:3001/assets/vendor.js:8252:12

vendor.js (line 21463)
jQuery.Deferred exception: input.size is not a function

dateTimePicker@http://0.0.0.0:3001/assets/vendor.js:70828:17
$.fn.datetimepicker/<@http://0.0.0.0:3001/assets/vendor.js:70883:46
.each@http://0.0.0.0:3001/assets/vendor.js:4982:10
jQuery.prototype.each@http://0.0.0.0:3001/assets/vendor.js:4771:10
$.fn.datetimepicker@http://0.0.0.0:3001/assets/vendor.js:70878:16
didInsertElement@http://0.0.0.0:3001/assets/vendor.js:72594:30
superWrapper@http://0.0.0.0:3001/assets/vendor.js:39640:17
CoreView<.trigger@http://0.0.0.0:3001/assets/vendor.js:58566:16
superWrapper@http://0.0.0.0:3001/assets/vendor.js:39640:17
Renderer.prototype.didInsertElement@http://0.0.0.0:3001/assets/vendor.js:29409:7
Renderer_dispatchLifecycleHooks@http://0.0.0.0:3001/assets/vendor.js:29321:11
Renderer_renderTopLevelView@http://0.0.0.0:3001/assets/vendor.js:29295:7
Queue.prototype.invoke@http://0.0.0.0:3001/assets/vendor.js:15823:9
Queue.prototype.flush@http://0.0.0.0:3001/assets/vendor.js:15889:11
DeferredActionQueues.prototype.flush@http://0.0.0.0:3001/assets/vendor.js:15697:11
Backburner.prototype.end@http://0.0.0.0:3001/assets/vendor.js:15011:9
Backburner.prototype.run@http://0.0.0.0:3001/assets/vendor.js:15133:13
Backburner.prototype.join@http://0.0.0.0:3001/assets/vendor.js:15153:16
run.join@http://0.0.0.0:3001/assets/vendor.js:38605:12
run.bind/<@http://0.0.0.0:3001/assets/vendor.js:38668:14
resolve/</mightThrow@http://0.0.0.0:3001/assets/vendor.js:8184:21
resolve/</process<@http://0.0.0.0:3001/assets/vendor.js:8252:12

undefined
vendor.js (line 8460)
TypeError: input.size is not a function

**Comment by ahlivehr** [comment]
I'm also getting the error "input.size is not a function". Is there a more robust example for how to get this to work for Ember 2? I'm also pretty new to Ember, so it might just be my lack of experience in getting this to work.

**Comment by ahlivehr** [comment]
@umeshblader3 I just saw this issue that's probably related to your problem: https://github.com/plusacht/ember-bootstrap-datetimepicker/issues/86.

**Comment by Voles** [comment]
@umeshblader3 @ahlivehr this has been fixed in [v1.1.0](https://github.com/plusacht/ember-bootstrap-datetimepicker/releases/tag/v1.1.0). Please let us know if you still encounter issues after updating.

**Comment by Voles** [comment]
@ahlivehr if you still have issues with `input.size`, can you create a new issue with some more details? Then we can take a closer look at what is going wrong.
