### ISSUE TITLE
Assertion Failed: You modified [PROPERTY] twice on [MODEL] in a single render, after update to Ember 2.10

### ISSUE THREAD

**Issue by jaredgalanis** [plusacht/ember-bootstrap-datetimepicker#89]
I'm getting an assertion when I click on any calendar icon in any of the instances of ember-bootstrap-datetimepicker.

```"Assertion Failed: You modified requisition.start_date twice on <frontend@model:requisition::ember935:null> in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details."```

This only occurs when I pass the updateDate value into the component with a value of closure action involving the mut of some property, but if you don't do this then this addon doesn't function.

I understand that this is an issue with the Glimmer 2 rendering engine which is part of Ember 2.10, but I'm not familiar enough with this addon to suggest a fix yet.

**Comment by jaredgalanis** [comment]
Apparently I was not passing down the value I was attempting to mutate into the component. As a result I think I was attempting to mutate that value on the parent. As soon as set a value for date on the component declaration, this error went away.

**Comment by lionelrudaz** [comment]
Hi @jaredgalanis, I've got the same issue, but I'm not sure to understand how you've fixed it.

Can you paste your code here?

Thanks in advance
