### ISSUE TITLE
Maintainer(s)

### ISSUE THREAD

**Issue by Voles** [plusacht/ember-bootstrap-datetimepicker#90]
Hi @ claudiocro,

First of all, thanks for your work developing this addon.
I'm wondering if you're up to allow extra maintainers.

I would be happy to help maintaining this addon by triaging issues, reviewing PR's and creating releases.

Thanks in advance 

:sunny:

**Comment by claudiocro** [comment]
Hi @Voles 

I'm totally up for extra maintainers. At the moment I work alot with react so I had no time to check all the pull requests. I would be very glad to have some help.

I first can give you some more github permission to this project and then add you to the publisher on npm. Is it ok for you?

There are 7 pull request already open and it would be good to start there.

What do you think?

**Comment by Voles** [comment]
@claudiocro good to hear. I'm definitely up to help with PR's!

**Comment by Voles** [comment]
@claudiocro how do you currently test new additions? I see the addon uses Ember v1.13.8, but there's support for:
* 1.11.3
* 1.12.1
* 1.13.3

I'm curious to hear about your workflow. I'd like to merge the PR's that provide support for v2.8 & upcoming versions, but not sure about how to test those versions with this addon.

Thanks very much in advance for your help.

**Comment by Voles** [comment]
@claudiocro do you maybe have some time to take a look at my question? Thanks a lot!

**Comment by jasonmit** [comment]
> @claudiocro how do you currently test new additions?

Is the question how do I target specific versions of Ember?  That is already covered via ember-try and here is the configuration for the versions that are targeted explicitly:
https://github.com/plusacht/ember-bootstrap-datetimepicker/blob/master/config/ember-try.js

> I'd like to merge the PR's that provide support for v2.8 & upcoming versions, but not sure about how to test those versions with this addon.

I'd be happy to help once you open a PR.  Hard for me to answer without knowing the scope of the PR.  Typically, nothing special is required.  As for the version matrix, that's just saying you need legacy support for Ember <= 1.13 support you should use 0.4.x as master is only >= 1.13

**Comment by Voles** [comment]
@jasonmit thanks! I didn't know about ember-try.
I've updated the CHANGELOG and created release notes for v1.1.0 you have published.
